// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6srTpHNvyFMJXGEoReUZayvf56imBLjY',
    appId: '1:953517918365:web:849efc11976b33bb8aec74',
    messagingSenderId: '953517918365',
    projectId: 'globalnet-258b5',
    authDomain: 'globalnet-258b5.firebaseapp.com',
    storageBucket: 'globalnet-258b5.firebasestorage.app',
    measurementId: 'G-C00FLWFCVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QJoi-3JJusNvnxsQ8_R30DbpLHDPiYw',
    appId: '1:953517918365:android:8e5cfc511aced8c68aec74',
    messagingSenderId: '953517918365',
    projectId: 'globalnet-258b5',
    storageBucket: 'globalnet-258b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkE6VN6BT9_OEb-SagXD4H0fBXMzKysUc',
    appId: '1:953517918365:ios:c2e40ef4f11d1f598aec74',
    messagingSenderId: '953517918365',
    projectId: 'globalnet-258b5',
    storageBucket: 'globalnet-258b5.firebasestorage.app',
    iosBundleId: 'com.example.appBerita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkE6VN6BT9_OEb-SagXD4H0fBXMzKysUc',
    appId: '1:953517918365:ios:c2e40ef4f11d1f598aec74',
    messagingSenderId: '953517918365',
    projectId: 'globalnet-258b5',
    storageBucket: 'globalnet-258b5.firebasestorage.app',
    iosBundleId: 'com.example.appBerita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6srTpHNvyFMJXGEoReUZayvf56imBLjY',
    appId: '1:953517918365:web:d4b6d0effba5dbac8aec74',
    messagingSenderId: '953517918365',
    projectId: 'globalnet-258b5',
    authDomain: 'globalnet-258b5.firebaseapp.com',
    storageBucket: 'globalnet-258b5.firebasestorage.app',
    measurementId: 'G-LE3KQG0DF7',
  );
}
